### ISSUE TITLE
displayIf overrite layout while false

### ISSUE THREAD

**Issue by ch4ika** [DevNatan/inventory-framework#428]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐛 Describe the bug

https://hastebin.com/share/urayitonaf.java

![Screenshot 2023-08-12 100034](https://github.com/DevNatan/inventory-framework/assets/104507238/ef2509b8-8fec-4e4f-9a53-ecde9b7efc5f)

I've set my layout to X, and if displayIf is false it shouldn't override at all.

### 💻 Platform

- [X] Bukkit
- [ ] Sponge
- [ ] Other

### ⭐ Server Version

Current: git-Purpur-2028 (MC: 1.20.1)* Previous: git-Purpur-2023 (MC: 1.20.1) * You are 2 version(s) behind Download the new version at: https://purpurmc.org/downloads

### 📚 Library Version

3.0.0-rc.1

**Comment by DevNatan** [comment]
@ch4ika This is expected to happen since Inventory Framework do not have an "overlap system" but for sure i'll made one before Release 3. I cant work on this for v3.0.0-rc.2 due to release schedule date, v3.0.0-rc.2 is scheduled for today 14 Aug 2023.

v3.0.0-rc.3 is scheduled for 7 days after the previous one so 21 Aug 2023 it will be available.

Sorry for late response :)
