### ISSUE TITLE
Question about the pagination

### ISSUE THREAD

**Issue by ch4ika** [DevNatan/inventory-framework#431]
Let's say I want to create a pagination, so far so good everything, but if I want to build the items individually that some glow some not only if permission is present, how would I do that? Because I would no longer get the player in the context.

```
    private State<Pagination> state = paginationState(
            (context) -> QuestPlugin.getInstance().getQuestManager().getQuests().values().stream().toList(),
            (item, quest) -> item.withItem(createQuestItem(quest, player.hasPermission(quest.getId)))
    );
```

```
    private ItemStack createQuestItem(Quest quest, boolean glow) {
        List<QuestReward> rewards = quest.getRewards();
        ItemBuilder item = new ItemBuilder(Material.FURNACE_MINECART).setDisplayName(quest.getName() + " §8(§e" + quest.getId() + "§8)").setLore(quest.getDescription());
        item.addLore("");
        item.addLore("§7Belohnungen:");
        item.setGlow(glow);
        if (rewards.isEmpty()) {
            item.addLore("§8» §c✘");
        } else {
            for (QuestReward reward : rewards) {
                RewardType type = reward.getType();
                switch (type) {
                    case ITEM -> item.addLore(Component.text("§8» §a" + type.name()).asComponent());
                    case GEMS -> item.addLore(Component.text("§8» §a").append(Component.text(" <dark_gray><gems>({amount}{gems})<dark_gray>").replaceText(builder -> builder.matchLiteral("{amount}").replacement(FormatUtil.CURRENCY.format(reward.getValue())))).asComponent());
                }
            }
        }
        return item.build();
    }
```

Would that be the way to do it?
```
    private State<Pagination> test = paginationState(
            (context) -> QuestPlugin.getInstance().getQuestManager().getQuests().values().stream().toList(),
            (item, quest) -> item.onRender(slot -> slot.setItem(createQuestItem(slot.getPlayer(), quest))));
```

Then I have one last question about the pagination, how does it look when I have data async with CompleteableFuture from the database.

Would I then simply pack an empty list into the state and add the load and in onRender?

**Comment by DevNatan** [comment]
@ch4ika Yes, your code is right, using `onRender(slot -> slot.setItem(item))` or `rendered(() -> item)` is the right way to do it. `onRender`/`rendered` reacts to updates, `withItem` not.
* `withItem` = static render
* `onRender`/`rendered` = dynamic render.

But, recentely [we had a issue](https://github.com/DevNatan/inventory-framework/pull/416) about usage of dynamic rendering (`item.onRender`/`item.rendered`) in pagination item factory and another issue related to [paginated items not reacting to updates](https://github.com/DevNatan/inventory-framework/pull/425) that will be fixed in v3.0.0-rc.2.

Now, the CompletableFuture issue: It *should* work in the same way as the sync one - provide a source provide that can be List/Function/CompletableFuture and the pagination updated once the internal pagination source update is completed, but, maybe you are the first user of such, soi  don't have a history of using CompletableFuture as a concrete pagination source provider to explain to u. Now that you've brought it up I'm going to take a closer look at it.

Thanks for opening issue about it.

**Comment by ch4ika** [comment]
I've been looking for good inventory frameworks for days and I find this one well documented and well structured.
Other inventory frameworks have way too much de-feather that you don't need or way too little.

As far as I know, there are no frameworks that deal with async pagination loading. I've read through everything here and know that it was once installed, but then discarded again.

Thanks for the answer.

**Comment by DevNatan** [comment]
@ch4ika It had on earlier versions for sure, i don't remember exactly why i didn't implement it in version 3+.

I made an initial experimental version of asynchronous pagination for use if you want to test it. Will be improved in the next releases.

See [Release v3.0.0-rc.2](https://github.com/DevNatan/inventory-framework/releases/tag/v3.0.0-rc.2).
