### ISSUE TITLE
Get Component from Context like getComponentsAt

### ISSUE THREAD

**Issue by ch4ika** [DevNatan/inventory-framework#473]
### First, a few things...

- [ ] Is your feature request related to a problem?
- [X] Will this feature just help you or is it something everyone needs?
- [ ] Have you tried to implement or *draft* this feature?
- [ ] Is your feature a breaking change?

### 😄 Describe the solution you'd like

there is a getComponentAt(slot)
whats about an getComponentAt(slot)

### 🧠 Describe alternatives you've considered

For example, since I use the onResume or sometimes want to update other components, I want to be on other slots while it makes sense to get a getComponentAt.

Don't know if that's part of it.
https://github.com/DevNatan/inventory-framework/pull/437

### 💻 Platform

- [X] Bukkit
- [ ] Sponge
- [ ] Other
- [ ] All

### ⭐ Version

3.0.0

**Comment by DevNatan** [comment]
@ch4ika `getComponentsAt(slot)` returns a List of Components because components can overlap each other, two or more components can be in the same slot. Example usage
https://github.com/DevNatan/inventory-framework/blob/ef81b9f85f4d8cd33c8978e46679223b33b72517/inventory-framework-platform-bukkit/src/main/java/me/devnatan/inventoryframework/IFInventoryListener.java#L45-L48

For your case, I think you want a way to update a component directly since you don't have a Component instance when using `slot`, `layoutSlot` etc. If what you want is: update a component manually (having its instance to update somehow by hand) then I can provide a user-friendly InventoryFramework idiomatic API for it.

And yes!! You got it, #437 is *something like* what you want but it's mean to be automatic. Some code was implemented here #466 but it's just a key as identifier than anything else.
